[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "2.2.10" }
pluginPublish = { module = "com.gradle.publish:plugin-publish-plugin", version = "2.0.0" }
deltaCoverage = { module = "io.github.gw-kit:delta-coverage-gradle", version = "3.4.2" }
jacocoTestkit = { module = "pl.droidsonroids.gradle.jacoco:pl.droidsonroids.gradle.jacoco", version = "1.0.12" }
