plugins {
    id 'java'
}

group 'org.example'

subprojects {
    apply plugin: 'java'

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:6.1.3'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
    }

    test {
        useJUnitPlatform()
    }
}

