name: basic-steps

on:
  workflow_call:
  push:
    branches:
      - 'develop'
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write

    env:
      GH_USER: ${{ github.actor }}
      GH_TOKEN: ${{ github.token }}
      gradle_cmd: "./gradlew --parallel --build-cache --console=plain --no-watch-fs "

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Build & Test
        run: ${gradle_cmd}  check jacocoTestReport --continue

      - name: Run Delta Coverage check
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'suppress-delta-coverage') }}
        run: ${gradle_cmd} deltaCoverage
          -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"
          -x test -x functionalTest
          --continue

      - name: Publish Coverage Summary
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        continue-on-error: true
        uses: gw-kit/delta-coverage-action@main

      - name: Add test results to PR
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
        continue-on-error: true
        with:
          files:
            'build/test-results/*/TEST-*.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
